[package]
name = "pichromatic-pipeline"
version = "0.1.0"
edition = "2021"
description = "A raw photo developing pipeline "
license = "MIT"

[lib]
name = "pichromatic_pipeline"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib", "staticlib"]

[profile.release]
panic = "unwind"

[dependencies]
pichromatic = { version = "0.1.0", path = "../pichromatic" }
serde = { version = "1.0.217", features = ["derive"] }
serde_plain = "1.0.2"
serde_json = "*"
toml = "0.8.20"
rayon = "1.10.0"
rawler = "*"
uuid = { version = "*", features = ["js"] }
wasm-bindgen = "*"
wasm-bindgen-futures = "0.4"
pollster = "0.3.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
getrandom = { version = "0.2.17", features = ["js"] }
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3", features = ["console", "OffscreenCanvas"] }
js-sys = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.17", features = ["js"] }


[[bin]]
name = "dump_schema"
path = "src/bin_schema.rs"
