image_urls = [
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Colorplus-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektachrome-cross-processed-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Ektar-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Gold-pushed-1-stop-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-160-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-plus21EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-plus2EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-400-pushed-1-stop-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-0EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-0EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-0EV-tungsten-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-0EV-tungsten-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-plus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-plus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-plus2EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-plus2V-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-minus1EV-Frontier.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Pictures-for-Slider-Comparison/Charts/Portra-800-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/C200-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-minus1EV-Noritsu.png",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-200-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Fuji-400-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NGH-II-800-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/NPS-160-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Natura-1600-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-160S-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Pro-400H-pushed-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-minus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-minus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-plus0EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Provia-100F-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-+0V-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-plus0EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-plus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-plus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-plus2EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Superia-400-plus2EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Velvia-50-minus1EV-Frontier.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Velvia-50-minus1EV-Noritsu.jpg",
    "https://colorprecision-cdn.s3.us-east-1.amazonaws.com/Exterior-Film-Scans-Tool/Charts/Velvia-50-minus2EV-Frontier.jpg",
]

import os
import time
import urllib.request

out_dir = os.path.join(os.path.dirname(__file__), "data")
os.makedirs(out_dir, exist_ok=True)

for url in image_urls:
    name = url.split("/")[-1]
    dest = os.path.join(out_dir, name)
    if not os.path.exists(dest) or os.path.getsize(dest) == 0:
        print(f"Downloading {name}...")
        for attempt in range(5):
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                with urllib.request.urlopen(req, timeout=30) as resp, open(dest, "wb") as f:
                    f.write(resp.read())
                break
            except Exception as e:
                print(f"  Attempt {attempt+1} failed for {name}: {e}")
                if os.path.exists(dest):
                    os.remove(dest)
                time.sleep(1)

print("Done!")


